@startmindmap mindmap
skinparam defaultFontName Comic Sans MS, PT Sans, Arial
<style>
mindmapDiagram {
	node {
		BackgroundColor white
		LineColor black
		FontColor black
		LineThickness 1
		RoundCorner 10
		FontSize 14
		Padding 10
	}
    :depth(0) {
		LineColor #ffd332
		LineThickness 3
		FontSize 20
    }
    :depth(1) {
		LineThickness 2
		FontSize 16
    }
	.green * {
		LineColor #6daa56
	}
	.lblue * {
		LineColor #8dd7cd
	}
	.orange * {
		LineColor #e5a935
	}
	.blue * {
		LineColor #4a98b6
	}
	.red * {
		LineColor #d2736c
	}
	.lgreen * {
		LineColor #bacc75
	}
	.violet * {
		LineColor #cc75cc
	}
	.dblue * {
		LineColor #3b229f
	}
	.dorange * {
		LineColor #864902
	}
    ' leafNode {
    '     BackgroundColor transparent
    '     LineColor transparent
    '     LineStyle 0
    '     RoundCorner 0
	' 	Padding 0 10
    ' }
}
</style>

* Рецепитто

** Пользователи <<green>>
*** Гость
****_ Поиск рецептов
****_ Просмотр рецептов
****_ Фильтрация
****_ Просмотр ингредиентов
*** Зарегистрированный
****_ Все функции гостя
****_ Добавление рецепта
****_ Редактирование своих рецептов
****_ Удаление своих рецептов
****_ Загрузка изображений
****_ Комментарии
****_ Избранное
****_ Оценка рецептов
*** Администратор
****_ Управление ингредиентами
****_ Управление категориями
****_ Модерация рецептов
****_ Управление пользователями
****_ Управление комментариями
****_ Просмотр статистики
****_ Регистрация пользователей

** Основные функции <<lblue>>
*** Поиск рецептов
****_ Только избранное
****_ По названию
****_ По ингредиентам
*****_ Содержит ингредиенты
*****_ Исключает ингредиенты
*****_ Содержит хотя бы один
*****_ Содержит все
****_ По категории
****_ По автору
****_ Сортировка
*****_ По рейтингу
*****_ По дате добавления
*****_ По времени приготовления
*****_ По сложности
****_ Фильтры
*****_ Время приготовления
*****_ Сложность
*** Просмотр рецепта
****_ Название
****_ Автор
****_ Главное изображение
****_ Галерея изображений
****_ Описание
****_ Список ингредиентов
****_ Шаги приготовления
****_ Время приготовления
*****_ Активное
*****_ Полное
****_ Сложность
****_ Комментарии
****_ Рейтинг
****_ Похожие рецепты
****_ Кнопка "добавить в избранное"
****_ Кнопка "оценить"
****_ Кнопка "поделиться"
*** Добавление рецепта
****_ Название
****_ Категория
****_ Список ингредиентов
*****_ Выбор из базы
*****_ Указание количества
*****_ Указание единицы измерения
*****_ Удобные поиск ингредиента по категориям
****_ Шаги приготовления
*****_ Текст шага
*****_ Изображения шага
****_ Главное изображение рецепта
****_ Галерея
****_ Время приготовления
*****_ Активное
*****_ Полное
****_ Сложность
****_ Предпросмотр рецепта
****_ Сохранение черновика
****_ Публикация
*** Редактирование рецепта
*** Удаление рецепта

** Категории рецептов <<red>>
***_ Завтраки
***_ Супы
***_ Основные блюда
***_ Салаты
***_ Выпечка
***_ Десерты
***_ Напитки
***_ Соусы

** Дополнительно <<violet>>
*** Нормализация данных
****_ Capitalize названий рецептов
****_ Capitalize ингредиентов
****_ Удаление лишних пробелов
****_ Приведение единиц измерения к стандарту
*** Экспорт
****_ Поделиться рецептом
****_ Печать рецепта

left side

** Модель данных <<blue>>
*** Пользователь
****_ id
****_ имя
****_ логин
****_ пароль
****_ роль
****_ дата регистрации
****_ аватар
*** Рецепт
****_ id
****_ название
****_ автор_id
****_ описание
****_ главное изображение
****_ время приготовления (активное)
****_ время приготовления (полное)
****_ сложность
****_ рейтинг
****_ количество оценок
****_ дата создания
****_ статус
*****_ черновик
*****_ опубликован
*****_ удалён
*** Ингредиент
****_ id
****_ название
****_ нормализованное название (для поиска)
****_ категория
*** Связь рецепт-ингредиент
****_ recipe_id
****_ ingredient_id
****_ количество
****_ единица измерения
*** Шаг рецепта
****_ id
****_ recipe_id
****_ номер шага
****_ текст
****_ изображение (nullable)
*** Изображение рецепта
****_ id
****_ recipe_id
****_ путь к файлу
****_ тип
*****_ главное
*****_ галерея
*** Комментарий
****_ id
****_ пользователь_id
****_ рецепт_id
****_ текст
****_ дата
*** Оценка
****_ пользователь_id
****_ рецепт_id
****_ рейтинг
*** Избранное
****_ пользователь_id
****_ рецепт_id
****_ дата добавления

** Frontend <<lgreen>>
*** Общая архитектура
****_ SPA приложение
****_ REST API
****_ Адаптивный дизайн
****_ Поддержка мобильных устройств
****_ PWA (установка как приложение)
*** Главная страница
****_ Поисковая строка
****_ Популярные рецепты
****_ Новые рецепты
****_ Категории рецептов
****_ Рекомендации
*** Страница поиска
****_ Поле поиска
****_ Автодополнение ингредиентов
****_ Выбор ингредиентов
*****_ обязательные
*****_ исключаемые
****_ Фильтры
*****_ категория
*****_ сложность
*****_ время приготовления
*****_ рейтинг
****_ Сортировка
****_ Список рецептов
*****_ карточки рецептов
*****_ фото
*****_ рейтинг
*****_время приготовления\n(активное и полное)
*****_ кнопка избранного
****_ Пагинация / бесконечная прокрутка
*** Страница рецепта
****_ Фото
****_ Описание
****_ Ингредиенты
****_ Шаги приготовления
****_ Комментарии
****_ Рейтинг
****_ Кнопки
*****_ добавить в избранное
*****_ поделиться
*****_ распечатать
****_ Блок похожих рецептов
****_ Блок рецептов автора
*** Страница добавления/ред рецепта
****_ Форма рецепта
****_ Добавление ингредиентов
****_ Автопоиск ингредиентов
****_ Drag&Drop загрузка изображений
****_ Добавление шагов
****_ Предпросмотр
****_ Сохранение черновика
****_ Публикация
*** Профиль пользователя
****_ Аватар
****_ Информация о пользователе
****_ Список рецептов пользователя
****_ Избранные рецепты
****_ История оценок
****_ Настройки профиля
****_ Управление своими рецептами
*** Админ-панель
****_ Управление пользователями
****_ Модерация рецептов
****_ Управление ингредиентами
****_ Управление категориями
****_ Просмотр статистики

@endmindmap